/**
 * Ask About Verdict Module
 *
 * A compact inline chat prompt module for the Verdict screen.
 * Provides contextual quick-ask chips and a message composer.
 * Routes to Chat tab with question prefilled.
 *
 * Features:
 * - Single-line message composer with send icon
 * - 3-4 DYNAMIC LLM-generated questions specific to THIS booking
 * - Passes context (route, prices, effective cost, CPP) to chat
 *
 * NEW-9 FIX: Questions are now generated by LLM for maximum relevance
 */

import React, { useState, useEffect, useRef } from 'react';
import { motion } from 'framer-motion';
import { Send, MessageCircle, Sparkles } from 'lucide-react';
import { cn } from '../../../lib/utils';

// ============================================
// TYPES
// ============================================

export interface VerdictContext {
  winner: 'portal' | 'direct' | 'award' | 'tie';
  winnerLabel: string;
  portalPrice: number;
  directPrice: number;
  effectiveCost?: number;
  portalMilesEarned?: number;
  directMilesEarned?: number;
  awardCpp?: number;
  creditApplied?: number;
  route?: string; // e.g., "JFK → LAX" or "Hotel Name • Location"
  tabMode?: 'cheapest' | 'max_value' | 'easiest';
  // NEW: Enhanced context for better suggested questions
  sellerType?: 'hotel_direct' | 'ota' | 'metasearch' | 'unknown';
  sellerName?: string;
  bookingType?: 'flight' | 'hotel' | 'vacation_rental';
  hasFxConversion?: boolean;
  fxCurrency?: string;
  priceDifference?: number; // Absolute dollar difference
  isPriceClose?: boolean; // Within ~$25 or 2%
  confidenceLevel?: 'high' | 'medium' | 'low';
  // NEW: Additional context for smarter questions
  airline?: string;
  departDate?: string;
  returnDate?: string;
  cabin?: string;
  hotelName?: string;
  nights?: number;
}

export interface AskAboutVerdictModuleProps {
  context: VerdictContext;
  onAskQuestion: (question: string, context: VerdictContext) => void;
  className?: string;
}

// ============================================
// PROMPT CHIP TYPE
// ============================================

interface PromptChip {
  id: string;
  text: string;
  shortText?: string;
}

// ============================================
// LLM-POWERED QUESTION GENERATION
// NEW-9: Dynamic, booking-specific questions via Groq
// ============================================

const QUESTION_GENERATION_PROMPT = `You are a helpful travel booking advisor. Generate exactly 4 short, specific questions a user might ask about THIS particular booking comparison.

BOOKING CONTEXT:
{{CONTEXT}}

RULES:
1. Questions must be SPECIFIC to this booking (mention route, prices, airlines, dates if provided)
2. Questions should help the user make a decision RIGHT NOW
3. Each question should be 8-15 words maximum
4. Focus on practical concerns: price accuracy, flexibility, loyalty, timing
5. NO generic questions like "Is this a good deal?" - be specific!
6. If FX conversion is involved, ask about rate accuracy
7. If prices are close, ask about tie-breakers (cancellation, support)
8. If credit is applied, ask about credit usage strategy

Return ONLY a JSON array of 4 strings (the questions), nothing else:
["question 1", "question 2", "question 3", "question 4"]`;

function buildContextForLLM(ctx: VerdictContext): string {
  const lines: string[] = [];
  
  // Booking type and route
  const isStay = ctx.bookingType === 'hotel' || ctx.bookingType === 'vacation_rental';
  if (isStay) {
    lines.push(`Booking type: ${ctx.bookingType === 'hotel' ? 'Hotel' : 'Vacation Rental'}`);
    if (ctx.hotelName) lines.push(`Property: ${ctx.hotelName}`);
    if (ctx.nights) lines.push(`Stay: ${ctx.nights} night${ctx.nights > 1 ? 's' : ''}`);
  } else {
    lines.push(`Booking type: Flight`);
    if (ctx.route) lines.push(`Route: ${ctx.route}`);
    if (ctx.airline) lines.push(`Airline: ${ctx.airline}`);
    if (ctx.cabin) lines.push(`Cabin: ${ctx.cabin}`);
  }
  
  if (ctx.departDate) lines.push(`Date: ${ctx.departDate}${ctx.returnDate ? ` - ${ctx.returnDate}` : ''}`);
  
  // Prices
  lines.push(`Portal price: $${ctx.portalPrice}`);
  lines.push(`Direct price: $${ctx.directPrice}`);
  const diff = Math.abs(ctx.portalPrice - ctx.directPrice);
  lines.push(`Price difference: $${diff.toFixed(0)}`);
  
  // Credit
  if (ctx.creditApplied && ctx.creditApplied > 0) {
    lines.push(`Travel credit applied: $${ctx.creditApplied}`);
  }
  
  // Miles
  if (ctx.portalMilesEarned && ctx.directMilesEarned) {
    const milesDiff = ctx.portalMilesEarned - ctx.directMilesEarned;
    lines.push(`Miles earned: Portal ${ctx.portalMilesEarned.toLocaleString()} vs Direct ${ctx.directMilesEarned.toLocaleString()} (${milesDiff > 0 ? '+' : ''}${milesDiff.toLocaleString()} via portal)`);
  }
  
  // Winner
  lines.push(`Recommendation: ${ctx.winnerLabel}`);
  
  // Special conditions
  if (ctx.hasFxConversion && ctx.fxCurrency) {
    lines.push(`⚠️ Currency conversion involved: ${ctx.fxCurrency} → USD`);
  }
  if (ctx.isPriceClose || diff < 30) {
    lines.push(`⚠️ Prices are very close - essentially a tie`);
  }
  if (ctx.sellerName && ctx.sellerType && ctx.sellerType !== 'unknown') {
    lines.push(`Direct seller: ${ctx.sellerName} (${ctx.sellerType})`);
  }
  if (ctx.tabMode) {
    lines.push(`User priority: ${ctx.tabMode === 'cheapest' ? 'Lowest cost' : ctx.tabMode === 'max_value' ? 'Best value (factoring miles)' : 'Easiest/most flexible'}`);
  }
  
  return lines.join('\n');
}

// Cache for generated questions to avoid re-generating on every render
const questionCache = new Map<string, PromptChip[]>();

function getCacheKey(ctx: VerdictContext): string {
  // Create a stable cache key from the most important context fields
  return JSON.stringify({
    route: ctx.route,
    portalPrice: ctx.portalPrice,
    directPrice: ctx.directPrice,
    winner: ctx.winner,
    creditApplied: ctx.creditApplied,
    tabMode: ctx.tabMode,
  });
}

async function generateQuestionsViaLLM(ctx: VerdictContext): Promise<PromptChip[]> {
  // Check cache first
  const cacheKey = getCacheKey(ctx);
  if (questionCache.has(cacheKey)) {
    return questionCache.get(cacheKey)!;
  }
  
  try {
    // Try to get API key from storage
    const storage = await chrome.storage.local.get(['groq_api_key', 'vx_api_key']);
    const apiKey = storage.groq_api_key || storage.vx_api_key;
    
    if (!apiKey) {
      console.log('[AskAboutVerdict] No API key found, using fallback questions');
      return generateFallbackQuestions(ctx);
    }
    
    // Build the prompt with context
    const contextStr = buildContextForLLM(ctx);
    const prompt = QUESTION_GENERATION_PROMPT.replace('{{CONTEXT}}', contextStr);
    
    // Call Groq API directly (lightweight, fast)
    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'llama-3.1-8b-instant', // Fast model for quick questions
        messages: [
          { role: 'user', content: prompt }
        ],
        temperature: 0.7,
        max_tokens: 300,
      }),
    });
    
    if (!response.ok) {
      console.warn('[AskAboutVerdict] API call failed:', response.status);
      return generateFallbackQuestions(ctx);
    }
    
    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || '';
    
    // Parse JSON array from response
    const jsonMatch = content.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      console.warn('[AskAboutVerdict] No JSON array in response');
      return generateFallbackQuestions(ctx);
    }
    
    const questions: string[] = JSON.parse(jsonMatch[0]);
    
    if (!Array.isArray(questions) || questions.length === 0) {
      return generateFallbackQuestions(ctx);
    }
    
    // Convert to PromptChip format
    const chips: PromptChip[] = questions.slice(0, 4).map((q, i) => ({
      id: `llm-q-${i}`,
      text: q,
      shortText: q.length > 40 ? q.substring(0, 37) + '...' : q,
    }));
    
    // Cache the result
    questionCache.set(cacheKey, chips);
    
    return chips;
  } catch (error) {
    console.error('[AskAboutVerdict] Error generating questions:', error);
    return generateFallbackQuestions(ctx);
  }
}

// ============================================
// SMART FALLBACK QUESTIONS (used when LLM unavailable)
// Context-aware, verdict-specific, and actionable
// ============================================

function generateFallbackQuestions(ctx: VerdictContext): PromptChip[] {
  const chips: PromptChip[] = [];
  const isStay = ctx.bookingType === 'hotel' || ctx.bookingType === 'vacation_rental';
  const diff = Math.abs(ctx.portalPrice - ctx.directPrice);
  const milesDiff = (ctx.portalMilesEarned || 0) - (ctx.directMilesEarned || 0);
  const portalWins = ctx.winner === 'portal';
  const directWins = ctx.winner === 'direct';
  const isTie = ctx.winner === 'tie' || diff < 25;
  
  // ============================================
  // QUESTION 1: Verdict-specific "challenge" question
  // Challenge the verdict to help user understand trade-offs
  // ============================================
  if (portalWins) {
    // Portal won - ask about what you might lose
    if (isStay) {
      chips.push({
        id: 'portal-tradeoff',
        text: 'Will I lose Marriott/Hilton elite night credits by booking portal?',
        shortText: 'Lose elite nights?',
      });
    } else {
      chips.push({
        id: 'portal-tradeoff',
        text: `What do I give up by booking Portal instead of direct with ${ctx.airline || 'the airline'}?`,
        shortText: 'What do I lose?',
      });
    }
  } else if (directWins) {
    // Direct won - ask about the miles you're missing
    chips.push({
      id: 'direct-tradeoff',
      text: `I'm missing ${milesDiff > 0 ? milesDiff.toLocaleString() : 'extra'} portal miles — is Direct really better?`,
      shortText: 'Why not portal?',
    });
  } else if (isTie) {
    chips.push({
      id: 'tie-breaker',
      text: `Both are within $${diff.toFixed(0)} — what's the tie-breaker?`,
      shortText: 'Tie-breaker?',
    });
  }
  
  // ============================================
  // QUESTION 2: Credit-specific (if applicable) or flexibility
  // ============================================
  if (ctx.creditApplied && ctx.creditApplied > 0) {
    // Credit is being used
    if (portalWins) {
      chips.push({
        id: 'credit-strategy',
        text: `Is now the right time to use my $${ctx.creditApplied} credit, or save it for a bigger trip?`,
        shortText: 'Save credit?',
      });
    } else {
      // Direct won even with credit available!
      chips.push({
        id: 'credit-unused',
        text: `You recommend Direct even with $${ctx.creditApplied} credit available — why?`,
        shortText: 'Why skip credit?',
      });
    }
  } else if (isStay) {
    chips.push({
      id: 'hotel-flex',
      text: `Can I cancel this ${ctx.hotelName || 'hotel'} for free if my plans change?`,
      shortText: 'Free cancellation?',
    });
  } else {
    chips.push({
      id: 'flight-flex',
      text: 'What if I need to change dates or cancel this flight?',
      shortText: 'Change/cancel?',
    });
  }
  
  // ============================================
  // QUESTION 3: Miles value / loyalty question
  // ============================================
  if (Math.abs(milesDiff) > 1000 && !portalWins) {
    // Significant miles difference and we're NOT recommending portal
    chips.push({
      id: 'miles-value',
      text: `Are ${milesDiff.toLocaleString()} extra portal miles worth $${(milesDiff * 0.018).toFixed(0)}?`,
      shortText: `${(milesDiff/1000).toFixed(0)}k miles = $${(milesDiff * 0.018).toFixed(0)}?`,
    });
  } else if (Math.abs(milesDiff) > 500 && portalWins) {
    chips.push({
      id: 'miles-earned',
      text: `How should I use the +${milesDiff.toLocaleString()} miles I'll earn on Portal?`,
      shortText: 'Best miles use?',
    });
  } else if (isStay) {
    chips.push({
      id: 'hotel-status',
      text: 'Will portal booking count toward my hotel elite status?',
      shortText: 'Elite status?',
    });
  } else {
    chips.push({
      id: 'airline-miles',
      text: `Will I earn ${ctx.airline || 'airline'} miles on both options?`,
      shortText: 'Airline miles?',
    });
  }
  
  // ============================================
  // QUESTION 4: Specific actionable question
  // Based on booking details and context
  // ============================================
  if (ctx.hasFxConversion && ctx.fxCurrency) {
    chips.push({
      id: 'fx-accuracy',
      text: `Is the ${ctx.fxCurrency} → USD conversion accurate? Any hidden FX fees?`,
      shortText: 'FX accurate?',
    });
  } else if (ctx.sellerType === 'ota' && directWins) {
    chips.push({
      id: 'ota-warning',
      text: `${ctx.sellerName || 'This'} is an OTA — is my booking still protected?`,
      shortText: 'OTA safe?',
    });
  } else if (ctx.isPriceClose && diff < 50) {
    chips.push({
      id: 'close-call',
      text: `With only $${diff.toFixed(0)} difference, when would ${portalWins ? 'Direct' : 'Portal'} be better?`,
      shortText: `When ${portalWins ? 'direct' : 'portal'}?`,
    });
  } else if (portalWins && ctx.effectiveCost && ctx.effectiveCost < ctx.directPrice) {
    chips.push({
      id: 'effective-cost',
      text: `How is Portal's effective cost only $${ctx.effectiveCost.toFixed(0)} when sticker is $${ctx.portalPrice}?`,
      shortText: 'Show the math?',
    });
  } else {
    // Default: specific "what about" question
    chips.push({
      id: 'alternative',
      text: portalWins
        ? 'When would booking Direct be worth it instead?'
        : 'When would Portal actually be the better choice?',
      shortText: portalWins ? 'When direct?' : 'When portal?',
    });
  }
  
  return chips.slice(0, 4);
}

// ============================================
// MAIN COMPONENT
// ============================================

export const AskAboutVerdictModule: React.FC<AskAboutVerdictModuleProps> = ({
  context,
  onAskQuestion,
  className,
}) => {
  const [inputValue, setInputValue] = useState('');
  const [promptChips, setPromptChips] = useState<PromptChip[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const contextRef = useRef(context);
  
  // Generate questions via LLM when context changes
  useEffect(() => {
    // Only regenerate if context actually changed meaningfully
    const cacheKey = getCacheKey(context);
    const prevCacheKey = getCacheKey(contextRef.current);
    
    if (cacheKey !== prevCacheKey || promptChips.length === 0) {
      contextRef.current = context;
      setIsGenerating(true);
      
      generateQuestionsViaLLM(context)
        .then((chips) => {
          setPromptChips(chips);
          setIsGenerating(false);
        })
        .catch(() => {
          // Fallback to static questions on error
          setPromptChips(generateFallbackQuestions(context));
          setIsGenerating(false);
        });
    }
  }, [context]);
  
  const handleSend = () => {
    if (!inputValue.trim()) return;
    onAskQuestion(inputValue.trim(), context);
    setInputValue('');
  };
  
  const handleChipClick = (chip: PromptChip) => {
    onAskQuestion(chip.text, context);
  };
  
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };
  
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.2, duration: 0.25 }}
      className={cn(
        'p-4 rounded-xl',
        'bg-white/[0.03] border border-white/[0.06]',
        'space-y-3',
        className
      )}
    >
      {/* Header */}
      <div className="flex items-center gap-2">
        <MessageCircle className="w-4 h-4 text-indigo-400" />
        <span className="text-xs font-medium text-white/70">
          Ask about this verdict
        </span>
        {isGenerating && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="flex items-center gap-1 text-[10px] text-indigo-400/60"
          >
            <Sparkles className="w-3 h-3" />
            <span>Generating questions...</span>
          </motion.div>
        )}
      </div>
      
      {/* Message Composer */}
      <div className="flex gap-2">
        <div className="flex-1 relative">
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Ask about this comparison..."
            className={cn(
              'w-full px-3 py-2.5 pr-10',
              'text-sm text-white placeholder:text-white/30',
              'bg-white/[0.04] border border-white/[0.08] rounded-lg',
              'focus:outline-none focus:border-indigo-500/40 focus:bg-white/[0.06]',
              'transition-all duration-150'
            )}
          />
        </div>
        <motion.button
          onClick={handleSend}
          disabled={!inputValue.trim()}
          whileTap={{ scale: 0.95 }}
          className={cn(
            'flex items-center justify-center',
            'w-10 h-10 rounded-lg',
            'transition-all duration-150',
            inputValue.trim()
              ? 'bg-indigo-500/20 border border-indigo-500/30 text-indigo-400 hover:bg-indigo-500/30'
              : 'bg-white/[0.04] border border-white/[0.06] text-white/30 cursor-not-allowed'
          )}
          aria-label="Send question"
        >
          <Send className="w-4 h-4" />
        </motion.button>
      </div>
      
      {/* Prompt Chips - LLM Generated */}
      {promptChips.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {promptChips.map((chip: PromptChip, index: number) => (
            <motion.button
              key={chip.id}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.3 + index * 0.05 }}
              onClick={() => handleChipClick(chip)}
              className={cn(
                'px-3 py-1.5 rounded-full',
                'text-xs text-white/60',
                'bg-white/[0.04] border border-white/[0.06]',
                'hover:bg-white/[0.08] hover:text-white/80 hover:border-white/[0.10]',
                'transition-all duration-150',
                'cursor-pointer'
              )}
            >
              {chip.shortText || chip.text}
            </motion.button>
          ))}
        </div>
      )}
      
      {/* Loading state while generating */}
      {isGenerating && promptChips.length === 0 && (
        <div className="flex gap-2">
          {[1, 2, 3].map((i) => (
            <div
              key={i}
              className="h-7 px-6 rounded-full bg-white/[0.02] border border-white/[0.04] animate-pulse"
            />
          ))}
        </div>
      )}
    </motion.div>
  );
};

export default AskAboutVerdictModule;
